### PR TITLE
update rapidsai/ci to rapidsai/ci-conda

### PR DESCRIPTION
**Pull request by AyodeAwe**
PR updates `rapidsai/ci` references to `rapidsai/ci-conda`.

### CODE REVIEW

**Comment by cwharris** [comment]
@dagardner-nv for viz

**Comment by ajschmidt8** [comment]
FWIW, this PR is effectively a no-op. We currently publish the same images to both the `rapidsai/ci` and `rapidsai/ci-conda` tags.

Once we've removed all the references to `rapidsai/ci`, we will remove them from DockerHub.

**Review by dagardner-nv — APPROVED** [review]

**Comment by ajschmidt8** [comment]
merging since this has been approved

**Pull request merged**
